### PR TITLE
Initial hero

### PR DESCRIPTION
**Pull request by amccloud**
WIP do not merge

### CODE REVIEW

**Comment by amccloud** [comment]
@zpnk thoughts? https://stagesh-ofdmvaqqnu.now.sh


btw is this repo setup to use stage.now.sh?

**Comment by amccloud** [comment]
Edit: updated link https://stagesh-ofdmvaqqnu.now.sh


...lol

**Comment by zpnk** [comment]
Oh man, this is amazing! The responsiveness is perfect.

Two small things:
- The animation of the initial commit and the browser seems to happen at once. It might make sense to delay the browser slightly so the pipeline order is more clear: branch commit -> now deploy -> qa pass -> master merge.
- From our conversation I understand the green circle represents the "qa pass", but if I didn't have that context I might not get it. Maybe a checkmark could better represent that idea? (fully understand this is more complicated in css, sorry :p)

**Comment by zpnk** [comment]
Otherwise this is good to go! Btw, does this pass the linter? I know it was complaining about defining `styles` for example after it is first used.

**Pull request merged**
